# Build arguments
ARG SOURCE_CODE=.
ARG CI_CONTAINER_VERSION="unknown"

# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:1.21 as builder

## Build args to be used at this step
ARG SOURCE_CODE

## CPaaS CODE BEGIN ##
COPY ${REMOTE_SOURCE} ${REMOTE_SOURCE_DIR}
ENV SOURCE_CODE=${REMOTE_SOURCE}/app
## CPaaS CODE END ##

WORKDIR /workspace
# Copy the Go Modules manifests
COPY ${SOURCE_CODE}/go.mod go.mod
COPY ${SOURCE_CODE}/go.sum go.sum
COPY ${SOURCE_CODE}/Makefile Makefile
RUN source ${CACHITO_ENV_FILE} && go mod download

# Copy the Go sources
COPY ${SOURCE_CODE}/main.go main.go
COPY ${SOURCE_CODE}/pkg/ pkg/

# Copy git info
COPY .git .git
RUN git config --global --add safe.directory /workspace

# Build
USER root
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 make go-build-for-image

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
## Build args to be used at this step
ARG SOURCE_CODE

## CPaaS CODE BEGIN ##
COPY ${REMOTE_SOURCE} ${REMOTE_SOURCE_DIR}
ENV SOURCE_CODE=${REMOTE_SOURCE}/app
## CPaaS CODE END ##

WORKDIR /
COPY --from=builder /workspace/manager .

USER 65532:65532
ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-codeflare-operator-container" \
      name="managed-open-data-hub/odh-codeflare-operator-container-rhel8" \
      version="${CI_CONTAINER_VERSION}" \
      git.url="${CI_CODEFLARE_OPERATOR_UPSTREAM_URL}" \
      git.commit="${CI_CODEFLARE_OPERATOR_UPSTREAM_COMMIT}" \
      summary="odh-codeflare-operator-container" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-codeflare-operator-container" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      description="Manages lifecycle of MCAD and InstaScale custom resources and associated Kubernetes resources" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"