resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: stack-config
  envs:
    - params.env
configurations:
  - params.yaml

# vars:
# - name: codeflare_operator_controller_image
#   objref:
#     kind: ConfigMap
#     name: stack-config
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.codeflare-operator-controller-image

replacements:
- source:
    kind: ConfigMap
    name: stack-config
    version: v1
  targets:
  - select:
      kind: Deployment
      name: manager
    fieldPaths:
    - spec.template.spec.containers.0.image